- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: pull docker image
      shell: docker pull anoushkachouksey/speminiproject:latest

    - name: run container
      shell: docker run -i -t --name calculator -d anoushkachouksey/speminiproject